language: java
env:
    global:
        - FILES="VERSION.h"

before_install:

script: 
#    - cd $PWD/javalin-rest
#    - mvn clean verify
    - git clone --depth=50 --branch=master https://github.com/doanthuyan/playground.git
    - git checkout master
    - if diff -w $PWD/VERSION $PWD/source/Sniffer/VERSION.h = 0 ; then
        echo "Version does not change";
        
      else
        echo "Version is not sync";
        cp $PWD/VERSION $PWD/source/Sniffer/VERSION.h ;
      fi
      
    - git remote
    - git config --global user.email "doanthuyan@gmail.com"
    - git config --global user.name "Travis CI"
    - git diff HEAD
    - git commit -m "Travis commit"
    - git push origin master:master > /dev/null 2>&1
