language: java
env:
    global:
        - FILES="VERSION.h"

before_install:

script: 
#    - cd $PWD/javalin-rest
#    - mvn clean verify
    - git clone --depth=50 --branch=master https://github.com/doanthuyan/playground.git
    - git checkout master
    - if diff -w $PWD/VERSION $PWD/source/Sniffer/VERSION.h = 0 ; then
        echo "Version does not change";
        
      else
        echo "Version is not sync";
        cat $PWD/VERSION && sleep 10;
        #cat $PWD/source/Sniffer/VERSION.h ;
        cp $PWD/VERSION $PWD/source/Sniffer/VERSION.h ;
        cat $PWD/source/Sniffer/VERSION.h && sleep 10;
        git remote
        git config --global user.email "doanthuyan@gmail.com"
        git config --global user.name "Travis CI"
        git diff HEAD
        git commit $PWD/source/Sniffer/VERSION.h -m "Travis commit"
        git push origin master:master > /dev/null 2>&1
      fi
      
    
