language: java

before_install:

script: 
#    - cd $PWD/javalin-rest
#    - mvn clean verify

    - if[[ `diff -w $PWD/VERSION $PWD/source/Sniffer/VERSION.h` != 0 ]]; then
        cp $PWD/VERSION $PWD/source/Sniffer/VERSION.h ;
        
      fi
