# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
url: "http://doanthuyan.github.io/playground"


title: An's playground
description: A playground for my stuffs while learning

markdown: kramdown
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
paginate: 5
